# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNPDMetronome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNPDMetronome
  pod 'libpd', :git => 'https://github.com/libpd/libpd', :submodules => true


end
